ku-cms/eLink_Instrumentation

python/create_all_s2p.py, python/readVNAData.py, python/readVNADataSKRF.py
- Update directory structure: separate data and plot directories
- Update format
=> Structure and Format Updates

VNA/python/draw_plots.py, VNA/python/plotVNAFeatures.py
Updates to draw_plots.py and plotVNAFeatures.py
- Create plots and calculate mean impedance for John's cable 3 (2 m)
- Rearrange options
- Add options
- Fix bug in x and y limit order
- Set limits for time domain plot
- Fix plot names
=> Update Impedance Plots

EyeDiagrams/python/makePlots.py
Print mean and std dev on eye diagram plots.
=> Small Plot Update

EyeDiagrams/README.md
=> Update Python Instructions

EyeDiagrams/python/makePlots.py, EyeDiagrams/python/plotComparisonMultiInput.py, EyeDiagrams/python/tools.py, VNA/python/draw_plots.py
- new script that accepts two eye diagram tables (csv files) and creates a comparison plot
- compare cables 120 and 121, old settings (ch1) vs. new settings (math1)
- calculate ratio of means with error (assuming no correlation... which is not true)
=> Eye Diagram Comparison Plots

EyeDiagrams/python/compPlots.py
Script for plotting eye diagram data from Jenna
=> Plotting eye diagram data

VNA/python/draw_plots.py, VNA/python/plotVNAFeatures.py
- Update draw_plots.py: use analyze function, specify different times per cable or channel
- Update plotVNAFeatures.py: add main() and analyze() functions and time window option (per cable or channel)
- Output csv file with results
=> Update VNA Scripts

EyeDiagrams/python/ErniePlot.py, EyeDiagrams/python/ErnieProcess.py, EyeDiagrams/python/makePlots.py, EyeDiagrams/python/makeTableScan.py, EyeDiagrams/python/processData.py, EyeDiagrams/scripts/process_scan.sh, VNA/python/VNA_COMP.py, VNA/python/draw_plots.py
- Update VNA script with production version from Windows computer on network R drive
- Path to production version of VNA analysis script on network R drive: R:\BEAN_GRP\4portvnadata\VNA_analysis\VNA_Comp.py
- Update eye diagram scripts
=> Update Analysis Scripts

VNA/python/VNA_COMP.py
- Fix bug: 2 of 5 channels were using hardcoded 2 to 5 ns time window, and others were variable time window; now all channels use the same variable time window
- Remove hardcoded number of channels; now run over any number of channels
=> VNA Script Update

VNA/README.md
Update VNA documentation (readme)
- Instructions for setting up python on Windows 10
- Instructions for using VNA_Comp.py to analyze VNA data
=> Update VNA Documentation

EyeDiagrams/README.md, EyeDiagrams/python/makePlots.py, EyeDiagrams/python/makeTableScan.py, EyeDiagrams/python/plotComparisonMultiInput.py, EyeDiagrams/scripts/process_scan.sh
RD53B Updates
- Process RD53B eye diagram data
- Plot RD53B eye diagram data
- Comparison plots for RD53 A, B eye diagram data
=> RD53B Updates

Analysis/python/analyze.py, Analysis/python/tools.py
New plots
- Plot RD53A_MinTAP0 vs area
- Plot impedance vs area
=> New plots!

VNA/python/VNA_COMP.py
Address this issue: https://github.com/ku-cms/eLink_Instrumentation/issues/37
VNA analysis updates:
- Improve formatting of output impedance values
- Fix frequency summary plot
- Fix axis limits
- Fix labels
- Fix grid major/minor emphasis
- Improve colors
TODO:
- Fix output csv files
=> Improve VNA analysis

VNA/python/VNA_COMP.py
Fix saved VNA impedance table
- Fix output csv files
- New table columns: Cable, Channel, Parameter, Mean Impedance (ohms), Comments
Improve method to get integration window
- Use function and dictionary to get window
=> VNA analysis fixes and improvements

EyeBERT/EyeBertAutomation.py, EyeBERT/create_scan_0.tcl
Automated eye-bert updates
- Add the TCL file create_scan_0.tcl
- Set TXDIFFSWING to "924 mV (1010)"
- Copy files to R drive
- Prompt user for operator name
- Add channel and operator columns
=> Automated eye-bert updates

EyeBERT/EyeBertAutomationDev.py, EyeBERT/template_analysis.py, EyeBERT/template_analysis_windows.py
Template analysis
- Now tested and working on Windows PC
- Creates template comparisons plots and copies these to the R drive
- Saves the number of "out points" (good) and "in points" (bad) to the results excel file
- Fixed various issues with file paths
- Fixed bug for file index >= 10
4-point DC resistance
- Now automated: prints values to screen
- Does not save values to excel file yet
=> Auto eye-bert updates

EyeBERT/EyeBertAutomationDev.py
Updates
- Check for bad (large) 4-point DC resistance measurements
- Save 4-point DC resistance values to a new excel file on the R drive
- Fix bug for new excel files: first check that excel file exists before checking if file is open; applies to DC resistance and eye-bert area excel files
- Add and rename variables
- Improve print statements
=> Auto DC + Eye BERT Updates

EyeBERT/EyeBertAutomationDev.py, EyeBERT/template_analysis_windows.py
Updates for TFPX Type 3.2 e-links
- User must now enter a valid cable type.
- If the cable type has branches, the user must enter a valid branch.
- The channel mapping is assigned based on the cable type.
- Different spreadsheets are used to save data for each cable type.
- The cable branch is saved in the spreadsheet (if applicable).
- The cable branch is used in the file name (if applicable).
TODO
- Add cable branch to the title of the template analysis plots.
- Simplify the function getIndexedFiles().
- Store list of channels for each type of cable.
=> Updates for TFPX Type 3.2 e-links

EyeBERT/EyeBertAutomationDev.py, EyeBERT/template_analysis_windows.py
TFPX Updates
- Nora added e-link branch to the template plots.
- Simplified tables headers: now support e-link branches and channels for all types.
- Simplified table dictionaries: now support e-link branches and channels for all types.
- Added relay board mapping, channels, and branches for all TFPX e-link types.
=> TFPX Updates

EyeBERT/EyeBertAutomationDev.py, EyeBERT/EyeBertAutomationRev2.py, EyeBERT/tools.py
Create utility python file
- Addresses this issue: https://github.com/ku-cms/eLink_Instrumentation/issues/59
- Created tools.py
- Added utility functions to tools.py
- Implemented functions from tools.py for the Rev A relay board
- Tested 4-point DC resistance and eye-bert area (using Rev A): everything is working!
TODO: Implement functions from tools.py for the Rev B relay board.
=> Create utility python file

EyeBERT/EyeBertAutomationRev2.py, EyeBERT/eyebertserial.py
Use tools functions in Rev B code.
Addresses this issue: https://github.com/ku-cms/eLink_Instrumentation/issues/59
Also includes some relay board control updates.
=> Use tools for Rev B

Analysis/README.md
- Create README.md in Analysis folder.
- Write instructions for creating a cumulative e-link production plot.
- Write instructions for creating an input file (.csv) with the latest e-link production data.
=> Create analysis instructions

Analysis/README.md, Analysis/python/analyzeElinkProduction.py, Analysis/python/prepareElinkProductionData.py, Analysis/python/tools.py
Wrote a new script to prepare e-link production data; addresses this issue: https://github.com/ku-cms/eLink_Instrumentation/issues/79
Updated the analysis instructions and included automated and manual methods for data preparation.
Download the latest e-link production spreadsheet `Harness_Serial_Number.xlsx` from Teams, and then run the script `prepareElinkProductionData.py` to take care of the rest. The script does the following:
- Add today's date to the Excel file name.
- Move the Excel file to your working area (data directory).
- Export the `Production` sheet to a .csv file.
=> New script to prepare e-link production data
